version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: agro_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*'

volumes:
  postgres_data:
